Repository Upvision/upvision.github.io, pull requests merged in 2020-10, with the labels that each got.

#7 Implement basic theme with template logo in 3d
  gatsby-browser.js
  gatsby-node.js
  package.json
  src/assets/logo.glb
  src/components/footer.js
  src/components/header.js
  src/components/hero.js
  src/components/image.js
  src/components/layout.css
  src/components/layout.js
  src/components/navbar.js
  src/css/footer.css
  src/css/global.css
  src/css/hero.css
  src/css/layout.css
  src/css/navbar.css
  src/images/bg.png
  src/pages/index.js
  yarn.lock
Labels: enhancement

#14 About page updates
  .gitignore
  package-lock.json
  package.json
  src/css/about.css
  src/pages/about.js
  src/pages/index.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#16 Several improvements.
  gatsby-browser.js
  package-lock.json
  package.json
  src/components/hero.js
  src/components/layout.js
  src/components/navbar.js
  src/css/about.css
  src/css/layout.css
  src/pages/404.js
  src/pages/about.js
  src/pages/index.js
Labels: bug, enhancement

#24 Added contact us page
  src/components/navbar.js
  src/css/contact.css
  src/pages/contactus.js
Labels: enhancement, hacktoberfest-accepted
